<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="18.0.2" />
    <PackageReference Include="Stride.BepuPhysics" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Engine" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Video" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Physics" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Navigation" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Particles" Version="4.3.0.2507" />
    <PackageReference Include="Stride.UI" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Core.Assets.CompilerApp" Version="4.3.0.2507" IncludeAssets="build;buildTransitive" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SUIMStride\SUIMStride.csproj" />
    <ProjectReference Include="..\..\SUIM\SUIM.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\skybox_texture_hdr.dds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SUIM\Components\Popup.suim">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SUIM\Components\ScreenOverlay.suim">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SUIM\Styles\Main.style">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SUIM\Views\MainView.suim">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>