<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="SUIM.Suim.targets" Pack="true" PackagePath="buildTransitive" />
    <None Include="**\*.suim" Pack="true" PackagePath="contentFiles\any\any\" />
  </ItemGroup>

</Project>
